import os

DISCORD_PUBLIC_WEBHOOK_URL = os.getenv("DISCORD_PUBLIC_WEBHOOK_URL")
DISCORD_PRIVATE_WEBHOOK_URL = os.getenv("DISCORD_PRIVATE_WEBHOOK_URL")
DISCORD_ERROR_WEBHOOK_URL = os.getenv("DISCORD_ERROR_WEBHOOK_URL")  # חדש

ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
NEWS_API_KEY = os.getenv("NEWS_API_KEY")

DEFAULT_STOP_LOSS_PERCENT = 3
DEFAULT_TAKE_PROFIT_PERCENT = 6

MARKET_OPEN_HOUR = 16  # 16:30 ישראל
MARKET_CLOSE_HOUR = 23  # 23:00 ישראל
TIMEZONE = "Asia/Jerusalem"

