# config.py

# ניהול סיכונים
STOP_LOSS_PERCENTAGE = 0.03  # 3%
TAKE_PROFIT_PERCENTAGE = 0.06  # 6%
RISK_REWARD_RATIO = 1 / 2  # יחס 1:2

# נפח מינימלי לסינון מניות
MIN_VOLUME = 500_000

# תנאי סף
MIN_AI_SCORE = 75
MIN_CONFIDENCE_SCORE = 70

# אזורי זמן ושעות מסחר
TIMEZONE = "Israel"
MARKET_OPEN_HOUR = 16
MARKET_CLOSE_HOUR = 23
EARLY_CLOSE_HOUR = 20
DST_MARKET_OPEN_HOUR = 15
DST_MARKET_CLOSE_HOUR = 21
DST_FINAL_SIGNAL_HOUR = 21
REGULAR_FINAL_SIGNAL_HOUR = 22
EARLY_FINAL_SIGNAL_HOUR = 19

# שעות פעילות פרה/אפטר מרקט
PRE_MARKET_START = 11
PRE_MARKET_END = 16
AFTER_MARKET_START = 23
AFTER_MARKET_END = 2

# דוחות
WEEKLY_REPORT_DAY = "Saturday"
WEEKLY_REPORT_HOUR = 12
MONTHLY_REPORT_DAY = 1
MONTHLY_REPORT_HOUR = 12

# AI דגלים
ENABLE_BULLISH_BEARISH_DISPLAY = True
